use_frameworks!

platform :ios, '10.0'

target 'JohnWick_Example' do
  pod 'JohnWick', :path => '../'

  target 'JohnWick_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
